use_frameworks!

platform :ios, '9.0'

target 'pod_test_Example' do
  #pod 'pod_test', :path => '../'
  pod 'pod_test',:podspec => '../pod_test.podspec'
  target 'pod_test_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
